server:
  port: 8080
  tomcat:
    connection-timeout: 1200000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://192.170.1.201:3306/jiie
    username: root
    password: JiieDBP#ssw0rd#Dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

picturepath:
  db-url: "/pic/"
  loading-url: "192.170.1.202:8090/"
  upload-url: "images/"
  watermark-url: "images/watermark/img-logo.png"